### ISSUE TITLE
Install Via Vim Plug

### ISSUE THREAD

**Issue by UnrealApex** [wfxr/code-minimap#72]
I know that your vim plugin [minimap.vim](https://github.com/wfxr/minimap.vim) can be installed using [vim-plug](https://github.com/junegunn/vim-plug) but would it also be possible to do the same for code-minimap?  I find it easier to install plugins and their dependencies exclusively via [vim-plug](https://github.com/junegunn/vim-plug).

**Comment by wfxr** [comment]
It's possible if you have rust toolchain installed:

```
Plug 'wfxr/minimap.vim', {'do': ':!cargo install --locked code-minimap'}
```

https://github.com/wfxr/minimap.vim#-installation

**Comment by UnrealApex** [comment]
Thank you for the quick reply! More specifically I was wondering if it is possible to install code-minimap without having Rust installed(I am too lazy to install it).

**Comment by UnrealApex** [comment]
I understand. I'll just install it using Scoop. Thanks!
